[tool.poetry]
name = "desim"
version = "0.1.1"
description = "Sensitivity calculator for DESHIMA 2.0"
license = "MIT"
authors = [
    "Akira Endo <a.endo@tudelft.nl>",
    "Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>",
]

[tool.poetry.dependencies]
python = "^3.6"
astropy = "^4.0"
dataclasses = { version = "^0.7", python = "~3.6" }
jupyter-io = "^0.1"
matplotlib = "^3.1"
numpy = "^1.17"
scipy = "^1.4"
pandas = ">= 0.25"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
black = "^19.10b0"
pytest = "^5.3"
jupyter = "^1.0"
jupyterlab = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
